export interface CoursePlatform {
  id: string;
  name: string;
  route: string;
  icon: string;
  color: string;
  enabled: boolean;
  authCheckCommand?: string;
}

export const COURSE_PLATFORMS: CoursePlatform[] = [
  {
    id: "hotmart",
    name: "Hotmart",
    route: "/courses/hotmart",
    icon: "hotmart",
    color: "#F04E23",
    enabled: true,
    authCheckCommand: "hotmart_check_session",
  },
  {
    id: "udemy",
    name: "Udemy",
    route: "/courses/udemy",
    icon: "udemy",
    color: "#A435F0",
    enabled: true,
    authCheckCommand: "udemy_check_session",
  },
  {
    id: "kiwify",
    name: "Kiwify",
    route: "/courses/kiwify",
    icon: "kiwify",
    color: "#22C55E",
    enabled: true,
    authCheckCommand: "kiwify_check_session",
  },
  {
    id: "gumroad",
    name: "Gumroad",
    route: "/courses/gumroad",
    icon: "gumroad",
    color: "#FF90E8",
    enabled: true,
  },
  {
    id: "teachable",
    name: "Teachable",
    route: "/courses/teachable",
    icon: "teachable",
    color: "#4B5563",
    enabled: false,
  },
  {
    id: "kajabi",
    name: "Kajabi",
    route: "/courses/kajabi",
    icon: "kajabi",
    color: "#2563EB",
    enabled: false,
  },
  {
    id: "skool",
    name: "Skool",
    route: "/courses/skool",
    icon: "skool",
    color: "#5865F2",
    enabled: false,
  },
  {
    id: "pluralsight",
    name: "Pluralsight",
    route: "/courses/pluralsight",
    icon: "pluralsight",
    color: "#E80A89",
    enabled: false,
  },
  {
    id: "greatcourses",
    name: "Wondrium",
    route: "/courses/greatcourses",
    icon: "greatcourses",
    color: "#1E3A5F",
    enabled: false,
  },
  {
    id: "masterclass",
    name: "MasterClass",
    route: "/courses/masterclass",
    icon: "masterclass",
    color: "#000000",
    enabled: false,
  },
  {
    id: "thinkific",
    name: "Thinkific",
    route: "/courses/thinkific",
    icon: "thinkific",
    color: "#4A90D9",
    enabled: false,
  },
  {
    id: "curseduca",
    name: "Curseduca",
    route: "/courses/curseduca",
    icon: "curseduca",
    color: "#6366F1",
    enabled: false,
  },
  {
    id: "cademi",
    name: "Cademi",
    route: "/courses/cademi",
    icon: "cademi",
    color: "#10B981",
    enabled: false,
  },
  {
    id: "cakto",
    name: "Cakto",
    route: "/courses/cakto",
    icon: "cakto",
    color: "#F59E0B",
    enabled: false,
  },
  {
    id: "kirvano",
    name: "Kirvano",
    route: "/courses/kirvano",
    icon: "kirvano",
    color: "#8B5CF6",
    enabled: true,
  },
  {
    id: "memberkit",
    name: "MemberKit",
    route: "/courses/memberkit",
    icon: "memberkit",
    color: "#3B82F6",
    enabled: false,
  },
  {
    id: "rocketseat",
    name: "Rocketseat",
    route: "/courses/rocketseat",
    icon: "rocketseat",
    color: "#8257E5",
    enabled: false,
  },
  {
    id: "grancursos",
    name: "Gran Cursos",
    route: "/courses/grancursos",
    icon: "grancursos",
    color: "#1D4ED8",
    enabled: false,
  },
  {
    id: "fluencyacademy",
    name: "Fluency Academy",
    route: "/courses/fluencyacademy",
    icon: "fluencyacademy",
    color: "#F97316",
    enabled: false,
  },
  {
    id: "datascienceacademy",
    name: "Data Science Academy",
    route: "/courses/datascienceacademy",
    icon: "datascienceacademy",
    color: "#059669",
    enabled: true,
  },
  {
    id: "medcel",
    name: "Medcel",
    route: "/courses/medcel",
    icon: "medcel",
    color: "#DC2626",
    enabled: true,
  },
  {
    id: "medcof",
    name: "Medcof",
    route: "/courses/medcof",
    icon: "medcof",
    color: "#0891B2",
    enabled: false,
  },
  {
    id: "medway",
    name: "Medway",
    route: "/courses/medway",
    icon: "medway",
    color: "#7C3AED",
    enabled: true,
  },
  {
    id: "afyainternato",
    name: "Afya Internato",
    route: "/courses/afyainternato",
    icon: "afyainternato",
    color: "#EF4444",
    enabled: true,
  },
  {
    id: "alpaclass",
    name: "AlpaClass",
    route: "/courses/alpaclass",
    icon: "alpaclass",
    color: "#14B8A6",
    enabled: true,
  },
  {
    id: "areademembros",
    name: "Area de Membros",
    route: "/courses/areademembros",
    icon: "areademembros",
    color: "#6B7280",
    enabled: false,
  },
  {
    id: "astronmembers",
    name: "Astron Members",
    route: "/courses/astronmembers",
    icon: "astronmembers",
    color: "#1E40AF",
    enabled: false,
  },
  {
    id: "eduzznutror",
    name: "Eduzz / Nutror",
    route: "/courses/eduzznutror",
    icon: "eduzznutror",
    color: "#EA580C",
    enabled: false,
  },
  {
    id: "entregadigital",
    name: "Entrega Digital",
    route: "/courses/entregadigital",
    icon: "entregadigital",
    color: "#4338CA",
    enabled: true,
  },
  {
    id: "greennclub",
    name: "Greenn Club",
    route: "/courses/greennclub",
    icon: "greennclub",
    color: "#16A34A",
    enabled: true,
  },
  {
    id: "themembers",
    name: "TheMembers",
    route: "/courses/themembers",
    icon: "themembers",
    color: "#9333EA",
    enabled: true,
  },
  {
    id: "voompplay",
    name: "Voomp Play",
    route: "/courses/voompplay",
    icon: "voompplay",
    color: "#0EA5E9",
    enabled: true,
  },
];
