//! Análise local: heurística de IA (listas do Pinterest Power Menu, MIT),
//! dHash para achar pins quase iguais e paleta de cores por k-means.

use std::collections::HashMap;

use serde::Serialize;

// ───────────────────────── IA ─────────────────────────

/// Frases explícitas (nível 3).
const AI_EXPLICIT: &[&str] = &[
    "#aigenerated",
    "ai generated",
    "ai-generated",
    "aigenerated",
    "generative ai",
    "genai",
    "made with ai",
    "created with ai",
    "created using ai",
    "ai created",
    "generated with ai",
    "generated by ai",
    "ai modified",
    "ai-modified",
    "gerado por ia",
    "gerada por ia",
    "feito com ia",
    "criado com ia",
    "arte ia",
    "imagem ia",
    "inteligencia artificial",
    "inteligência artificial",
];
/// Ferramentas e termos comuns (nível 2).
const AI_TOOLS: &[&str] = &[
    "midjourney",
    "dall-e",
    "dall·e",
    "dalle",
    "stable diffusion",
    "ai art",
    "ai-art",
    "aiart",
    "ai image",
    "ai images",
    "ai artwork",
    "ai generated art",
    "ai illustration",
    "adobe firefly",
    "nightcafe",
    "leonardo ai",
    "leonardo.ai",
    "ai model",
    "text to image",
    "text-to-image",
    "sora ai",
    "flux ai",
    "comfyui",
    "automatic1111",
    "gpt image",
    "ideogram",
    "niji",
    "civitai",
    "lora",
    "sdxl",
    "imagen 3",
    "nano banana",
    "gemini image",
    "chatgpt image",
    "grok imagine",
    "ai photo",
    "ai portrait",
    "ai wallpaper",
    "ai aesthetic",
    "ai girl",
    "ai boy",
    "ai fashion",
];

/// Devolve (nível, termo que bateu). 1 = só a palavra "ai"/"ia" isolada.
pub fn ai_keyword_level(text_lower: &str) -> (u8, Option<String>) {
    for p in AI_EXPLICIT {
        if text_lower.contains(p) {
            return (3, Some((*p).to_string()));
        }
    }
    for p in AI_TOOLS {
        if text_lower.contains(p) {
            return (2, Some((*p).to_string()));
        }
    }
    let weak = regex::Regex::new(r"(?:^|[^a-z0-9])(?:ai|a\.i\.|#ai|ia)(?:$|[^a-z0-9])").unwrap();
    if weak.is_match(text_lower)
        || text_lower.contains("prompt:")
        || text_lower.contains("ai prompt")
    {
        return (1, Some("ai".into()));
    }
    (0, None)
}

// ───────────────────────── dHash ─────────────────────────

/// dHash 64 bits (9×8, diferença horizontal). Aceita jpg/png/webp/gif.
pub fn dhash(bytes: &[u8]) -> Option<u64> {
    let img = image::load_from_memory(bytes).ok()?;
    let g = image::imageops::resize(&img.to_luma8(), 9, 8, image::imageops::FilterType::Triangle);
    let mut h = 0u64;
    for y in 0..8 {
        for x in 0..8 {
            let a = g.get_pixel(x, y)[0];
            let b = g.get_pixel(x + 1, y)[0];
            h = (h << 1) | u64::from(a > b);
        }
    }
    Some(h)
}

pub fn hamming(a: u64, b: u64) -> u32 {
    (a ^ b).count_ones()
}

#[derive(Debug, Clone, Serialize)]
pub struct DupeGroup {
    /// "exact" (mesma image_signature) | "near" (dHash parecido)
    pub kind: String,
    pub ids: Vec<String>,
    /// maior distância dentro do grupo (0 para exatos)
    pub distance: u32,
}

/// Agrupa por assinatura igual e depois por dHash (união-busca).
pub fn group_dupes(
    items: &[(String, Option<String>, Option<u64>)],
    threshold: u32,
) -> Vec<DupeGroup> {
    let n = items.len();
    let mut parent: Vec<usize> = (0..n).collect();
    fn find(p: &mut [usize], i: usize) -> usize {
        let mut i = i;
        while p[i] != i {
            p[i] = p[p[i]];
            i = p[i];
        }
        i
    }
    fn unite(p: &mut [usize], a: usize, b: usize) {
        let (ra, rb) = (find(p, a), find(p, b));
        if ra != rb {
            p[ra] = rb;
        }
    }
    let mut by_sig: HashMap<&str, usize> = HashMap::new();
    let mut exact_pairs = 0usize;
    for (i, (_, sig, _)) in items.iter().enumerate() {
        if let Some(sig) = sig.as_deref() {
            if let Some(&j) = by_sig.get(sig) {
                unite(&mut parent, i, j);
                exact_pairs += 1;
            } else {
                by_sig.insert(sig, i);
            }
        }
    }
    let _ = exact_pairs;
    let mut dist: HashMap<(usize, usize), u32> = HashMap::new();
    #[allow(clippy::needless_range_loop)]
    for i in 0..n {
        let Some(hi) = items[i].2 else { continue };
        for j in (i + 1)..n {
            let Some(hj) = items[j].2 else { continue };
            let d = hamming(hi, hj);
            if d <= threshold {
                unite(&mut parent, i, j);
                dist.insert((i, j), d);
            }
        }
    }
    let mut groups: HashMap<usize, Vec<usize>> = HashMap::new();
    for i in 0..n {
        let r = find(&mut parent, i);
        groups.entry(r).or_default().push(i);
    }
    let mut out = Vec::new();
    for (_, members) in groups {
        if members.len() < 2 {
            continue;
        }
        let sigs: Vec<Option<&str>> = members.iter().map(|&i| items[i].1.as_deref()).collect();
        let all_same_sig = sigs.iter().all(|s| s.is_some() && *s == sigs[0]);
        let mut maxd = 0u32;
        for a in 0..members.len() {
            for b in (a + 1)..members.len() {
                let (i, j) = (members[a].min(members[b]), members[a].max(members[b]));
                if let Some(d) = dist.get(&(i, j)) {
                    maxd = maxd.max(*d);
                } else if let (Some(hi), Some(hj)) = (items[i].2, items[j].2) {
                    maxd = maxd.max(hamming(hi, hj));
                }
            }
        }
        out.push(DupeGroup {
            kind: if all_same_sig {
                "exact".into()
            } else {
                "near".into()
            },
            ids: members.iter().map(|&i| items[i].0.clone()).collect(),
            distance: if all_same_sig { 0 } else { maxd },
        });
    }
    out.sort_by(|a, b| {
        a.distance
            .cmp(&b.distance)
            .then(b.ids.len().cmp(&a.ids.len()))
    });
    out
}

// ───────────────────────── paleta ─────────────────────────

#[derive(Debug, Clone, Serialize)]
pub struct Swatch {
    pub hex: String,
    pub rgb: [u8; 3],
    /// fração 0..1 dos pixels/amostras que caíram nessa cor
    pub share: f32,
}

pub fn parse_hex(h: &str) -> Option<[u8; 3]> {
    let t = h.trim().trim_start_matches('#');
    if t.len() != 6 {
        return None;
    }
    let v = u32::from_str_radix(t, 16).ok()?;
    Some([(v >> 16) as u8, (v >> 8) as u8, v as u8])
}

pub fn to_hex(c: [u8; 3]) -> String {
    format!("#{:02x}{:02x}{:02x}", c[0], c[1], c[2])
}

/// Amostra pixels de uma imagem (pula os quase brancos/pretos quando pedido).
pub fn sample_pixels(bytes: &[u8], max_samples: usize, skip_extremes: bool) -> Vec<[u8; 3]> {
    let Ok(img) = image::load_from_memory(bytes) else {
        return Vec::new();
    };
    let small = image::imageops::resize(
        &img.to_rgb8(),
        48,
        48,
        image::imageops::FilterType::Triangle,
    );
    let mut out = Vec::with_capacity(max_samples.min(48 * 48));
    for p in small.pixels() {
        let [r, g, b] = p.0;
        if skip_extremes {
            let max = r.max(g).max(b) as i32;
            let min = r.min(g).min(b) as i32;
            if max > 245 && max - min < 12 {
                continue;
            }
            if max < 18 {
                continue;
            }
        }
        out.push([r, g, b]);
        if out.len() >= max_samples {
            break;
        }
    }
    out
}

fn dist2(a: [f32; 3], b: [f32; 3]) -> f32 {
    (a[0] - b[0]).powi(2) + (a[1] - b[1]).powi(2) + (a[2] - b[2]).powi(2)
}

/// k-means simples em RGB, inicializado por k-means++ determinístico.
pub fn kmeans_palette(samples: &[[u8; 3]], k: usize) -> Vec<Swatch> {
    if samples.is_empty() || k == 0 {
        return Vec::new();
    }
    let pts: Vec<[f32; 3]> = samples
        .iter()
        .map(|c| [c[0] as f32, c[1] as f32, c[2] as f32])
        .collect();
    let k = k.min(pts.len());
    let mut centers: Vec<[f32; 3]> = vec![pts[0]];
    while centers.len() < k {
        let mut best = (0usize, -1.0f32);
        for (i, p) in pts.iter().enumerate() {
            let d = centers
                .iter()
                .map(|c| dist2(*p, *c))
                .fold(f32::MAX, f32::min);
            if d > best.1 {
                best = (i, d);
            }
        }
        if best.1 <= 0.0 {
            break;
        }
        centers.push(pts[best.0]);
    }
    let mut assign = vec![0usize; pts.len()];
    for _ in 0..12 {
        for (i, p) in pts.iter().enumerate() {
            let mut bi = 0;
            let mut bd = f32::MAX;
            for (j, c) in centers.iter().enumerate() {
                let d = dist2(*p, *c);
                if d < bd {
                    bd = d;
                    bi = j;
                }
            }
            assign[i] = bi;
        }
        let mut sums = vec![[0f32; 4]; centers.len()];
        for (i, p) in pts.iter().enumerate() {
            let s = &mut sums[assign[i]];
            s[0] += p[0];
            s[1] += p[1];
            s[2] += p[2];
            s[3] += 1.0;
        }
        for (j, c) in centers.iter_mut().enumerate() {
            if sums[j][3] > 0.0 {
                *c = [
                    sums[j][0] / sums[j][3],
                    sums[j][1] / sums[j][3],
                    sums[j][2] / sums[j][3],
                ];
            }
        }
    }
    let mut counts = vec![0usize; centers.len()];
    for a in &assign {
        counts[*a] += 1;
    }
    let total = pts.len() as f32;
    let mut out: Vec<Swatch> = centers
        .iter()
        .zip(counts.iter())
        .filter(|(_, c)| **c > 0)
        .map(|(c, cnt)| {
            let rgb = [c[0].round() as u8, c[1].round() as u8, c[2].round() as u8];
            Swatch {
                hex: to_hex(rgb),
                rgb,
                share: *cnt as f32 / total,
            }
        })
        .collect();
    out.sort_by(|a, b| {
        b.share
            .partial_cmp(&a.share)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ai_levels() {
        assert_eq!(ai_keyword_level("beautiful ai generated cottage").0, 3);
        assert_eq!(ai_keyword_level("made in midjourney v6").0, 2);
        assert_eq!(ai_keyword_level("rain in spain").0, 0);
        assert_eq!(ai_keyword_level("#ai portrait").0, 2);
        assert_eq!(ai_keyword_level("my #ai experiment").0, 1);
        assert_eq!(ai_keyword_level("hair styles").0, 0);
    }

    #[test]
    fn groups_exact_and_near() {
        let items = vec![
            ("a".to_string(), Some("s1".to_string()), Some(0u64)),
            ("b".to_string(), Some("s1".to_string()), Some(0u64)),
            ("c".to_string(), Some("s2".to_string()), Some(0b11u64)),
            ("d".to_string(), Some("s3".to_string()), Some(u64::MAX)),
        ];
        let g = group_dupes(&items, 4);
        assert_eq!(g.len(), 1);
        assert_eq!(g[0].ids.len(), 3);
        assert_eq!(g[0].kind, "near");
        let g2 = group_dupes(&items[..2], 4);
        assert_eq!(g2[0].kind, "exact");
    }

    #[test]
    fn palette_from_samples() {
        let mut s = Vec::new();
        for _ in 0..50 {
            s.push([255u8, 0, 0]);
        }
        for _ in 0..30 {
            s.push([0u8, 0, 255]);
        }
        let p = kmeans_palette(&s, 2);
        assert_eq!(p.len(), 2);
        assert_eq!(p[0].hex, "#ff0000");
        assert!((p[0].share - 0.625).abs() < 0.01);
    }

    #[test]
    fn hex_roundtrip() {
        assert_eq!(parse_hex("#886d4c"), Some([0x88, 0x6d, 0x4c]));
        assert_eq!(to_hex([0x88, 0x6d, 0x4c]), "#886d4c");
    }
}
