pub mod auth;
pub mod autostart;
pub mod diagnostics;
pub mod downloads;
pub mod integration;
pub mod p2p;
pub mod platform_auth;
pub mod settings;
pub mod telegram;

#[cfg(not(target_os = "android"))]
pub mod convert;
#[cfg(not(target_os = "android"))]
pub mod courses;
#[cfg(not(target_os = "android"))]
pub mod dependencies;
#[cfg(not(target_os = "android"))]
pub mod search;
#[cfg(not(target_os = "android"))]
pub mod udemy_auth;
#[cfg(not(target_os = "android"))]
pub mod udemy_courses;
#[cfg(not(target_os = "android"))]
pub mod udemy_downloads;
#[cfg(not(target_os = "android"))]
pub mod kiwify;
#[cfg(not(target_os = "android"))]
pub mod greenn;
#[cfg(not(target_os = "android"))]
pub mod voomp;
#[cfg(not(target_os = "android"))]
pub mod entregadigital;
#[cfg(not(target_os = "android"))]
pub mod alpaclass;
#[cfg(not(target_os = "android"))]
pub mod themembers;
#[cfg(not(target_os = "android"))]
pub mod gumroad;
#[cfg(not(target_os = "android"))]
pub mod kirvano;
#[cfg(not(target_os = "android"))]
pub mod dsa;
#[cfg(not(target_os = "android"))]
pub mod medcel;
#[cfg(not(target_os = "android"))]
pub mod afya;
#[cfg(not(target_os = "android"))]
pub mod medway;
#[cfg(not(target_os = "android"))]
pub mod estrategia_concursos;
#[cfg(not(target_os = "android"))]
pub mod estrategia_ldi;
#[cfg(not(target_os = "android"))]
pub mod estrategia_militares;
#[cfg(not(target_os = "android"))]
pub mod grancursos;
#[cfg(not(target_os = "android"))]
pub mod skool;
#[cfg(not(target_os = "android"))]
pub mod teachable;
#[cfg(not(target_os = "android"))]
pub mod kajabi;
#[cfg(not(target_os = "android"))]
pub mod fluencyacademy;
#[cfg(not(target_os = "android"))]
pub mod nutror;
#[cfg(not(target_os = "android"))]
pub mod cademi_cmd;
#[cfg(not(target_os = "android"))]
pub mod memberkit_cmd;
#[cfg(not(target_os = "android"))]
pub mod areademembros;
#[cfg(not(target_os = "android"))]
pub mod astronmembers;
#[cfg(not(target_os = "android"))]
pub mod cakto;
#[cfg(not(target_os = "android"))]
pub mod caktomembers;
#[cfg(not(target_os = "android"))]
pub mod curseduca;
#[cfg(not(target_os = "android"))]
pub mod medcof;
#[cfg(not(target_os = "android"))]
pub mod thinkific;
#[cfg(not(target_os = "android"))]
pub mod rocketseat;
#[cfg(not(target_os = "android"))]
pub mod pluralsight;
#[cfg(not(target_os = "android"))]
pub mod greatcourses;
#[cfg(not(target_os = "android"))]
pub mod masterclass;
