//! Docker provider: a minimal image per tool (Dockerfile generated into
//! `<app_data>/sandbox/<tool>/`), the project copied into the run folder and
//! mounted at `/work`, the tool's API key passed as `-e NAME` with the value
//! only in the docker client's environment.

use std::path::Path;
use std::time::Duration;

use sha2::{Digest, Sha256};
use tokio_util::sync::CancellationToken;

use super::super::runner::{self, RunOutput, ToolRun};
use super::{key_env, root, run_dir, save_record, tree, RunRecord, SandboxOpts, ERR_SANDBOX};
use crate::core::llm::drivers::acp::proc;

/// Tools the generated image knows how to install (npm package).
pub const SUPPORTED: &[(&str, &str)] = &[
    ("claude", "@anthropic-ai/claude-code"),
    ("codex", "@openai/codex"),
    ("gemini", "@google/gemini-cli"),
    ("qwen", "@qwen-code/qwen-code"),
    ("opencode", "opencode-ai"),
];

pub fn package_of(tool: &str) -> Option<&'static str> {
    SUPPORTED.iter().find(|(t, _)| *t == tool).map(|(_, p)| *p)
}

/// The Dockerfile for `tool`: Node slim, git, ripgrep, the CLI, non-root user.
pub fn dockerfile(tool: &str) -> Result<String, String> {
    let pkg = package_of(tool).ok_or_else(|| {
        format!(
            "{ERR_SANDBOX}: no sandbox image for `{tool}` (supported: {})",
            SUPPORTED
                .iter()
                .map(|(t, _)| *t)
                .collect::<Vec<_>>()
                .join(", ")
        )
    })?;
    Ok(format!(
        "# Generated by OmniGet (sandbox recipe). Rebuilt when this text changes.\n\
FROM node:22-bookworm-slim\n\
RUN apt-get update \\\n && apt-get install -y --no-install-recommends git ca-certificates ripgrep curl python3 \\\n && rm -rf /var/lib/apt/lists/*\n\
RUN npm install -g {pkg} && npm cache clean --force\n\
ENV DISABLE_AUTOUPDATER=1 CI=1\n\
USER node\n\
WORKDIR /work\n"
    ))
}

pub fn image_tag(tool: &str, dockerfile: &str) -> String {
    let h = hex::encode(Sha256::digest(dockerfile.as_bytes()));
    format!("omniget-sandbox-{tool}:{}", &h[..12])
}

/// `{available, version, error}`; a missing daemon is a clear message.
pub async fn probe() -> serde_json::Value {
    let Some(bin) = proc::which("docker") else {
        return serde_json::json!({ "available": false, "error": "Docker is not installed (docker was not found on the PATH)" });
    };
    let out = tokio::time::timeout(
        Duration::from_secs(8),
        crate::core::process::command(&bin)
            .args(["version", "--format", "{{.Server.Version}}"])
            .output(),
    )
    .await;
    match out {
        Ok(Ok(o)) if o.status.success() => serde_json::json!({
            "available": true,
            "version": String::from_utf8_lossy(&o.stdout).trim(),
            "path": bin.to_string_lossy(),
        }),
        Ok(Ok(o)) => serde_json::json!({
            "available": false,
            "error": format!("Docker is installed but the daemon is not answering: {}", String::from_utf8_lossy(&o.stderr).lines().last().unwrap_or("").trim()),
        }),
        Ok(Err(e)) => serde_json::json!({ "available": false, "error": e.to_string() }),
        Err(_) => {
            serde_json::json!({ "available": false, "error": "docker version timed out (is the daemon starting?)" })
        }
    }
}

async fn docker(args: &[&str]) -> Result<std::process::Output, String> {
    crate::core::process::command("docker")
        .args(args)
        .output()
        .await
        .map_err(|e| format!("{ERR_SANDBOX}: docker: {e}"))
}

/// Builds the image once per Dockerfile text.
pub async fn ensure_image(
    tool: &str,
    on_log: &mut (dyn FnMut(&str) + Send),
) -> Result<String, String> {
    let text = dockerfile(tool)?;
    let tag = image_tag(tool, &text);
    let have = docker(&["image", "inspect", &tag]).await?;
    if have.status.success() {
        return Ok(tag);
    }
    let dir = root()?.join(tool);
    std::fs::create_dir_all(&dir).map_err(|e| format!("{ERR_SANDBOX}: {e}"))?;
    std::fs::write(dir.join("Dockerfile"), &text).map_err(|e| format!("{ERR_SANDBOX}: {e}"))?;
    on_log(&format!(
        "· building {tag} (first run of the {tool} sandbox)"
    ));
    let out = crate::core::process::command("docker")
        .args(["build", "-t", &tag])
        .arg(&dir)
        .output()
        .await
        .map_err(|e| format!("{ERR_SANDBOX}: docker build: {e}"))?;
    if !out.status.success() {
        let err = String::from_utf8_lossy(&out.stderr);
        let last: Vec<&str> = err.lines().rev().take(6).collect();
        return Err(format!(
            "{ERR_SANDBOX}: docker build failed: {}",
            last.into_iter().rev().collect::<Vec<_>>().join(" | ")
        ));
    }
    Ok(tag)
}

fn mount(host: &Path) -> String {
    format!("{}:/work", host.to_string_lossy())
}

/// The `docker run` argv (pure; the key values are not in it).
pub fn run_args(
    name: &str,
    image: &str,
    work: &Path,
    env_names: &[String],
    network: bool,
    launch: &runner::Launch,
) -> Vec<String> {
    let mut a: Vec<String> = vec![
        "run".into(),
        "--rm".into(),
        "-i".into(),
        "--name".into(),
        name.into(),
        "-v".into(),
        mount(work),
        "-w".into(),
        "/work".into(),
    ];
    // Docker Desktop maps file ownership for bind mounts; a Linux daemon does
    // not, so the container runs as the user who owns the copy.
    #[cfg(target_os = "linux")]
    {
        // SAFETY: plain getters.
        let (uid, gid) = unsafe { (libc::getuid(), libc::getgid()) };
        a.push("--user".into());
        a.push(format!("{uid}:{gid}"));
        a.push("-e".into());
        a.push("HOME=/tmp".into());
    }
    if !network {
        a.push("--network".into());
        a.push("none".into());
    }
    for n in env_names {
        a.push("-e".into());
        a.push(n.clone());
    }
    a.push(image.into());
    a.push(launch.program.clone());
    a.extend(launch.args.iter().cloned());
    a
}

pub async fn run(
    id: &str,
    run: &ToolRun,
    opts: &SandboxOpts,
    cancel: CancellationToken,
    on_log: &mut (dyn FnMut(&str) + Send),
) -> Result<(RunOutput, RunRecord), String> {
    let st = probe().await;
    if st["available"].as_bool() != Some(true) {
        return Err(format!(
            "{ERR_SANDBOX}: Docker unavailable: {}",
            st["error"].as_str().unwrap_or("unknown")
        ));
    }
    let project = run
        .cwd
        .clone()
        .ok_or_else(|| format!("{ERR_SANDBOX}: a sandbox run needs a project folder"))?;
    let (target, rc) = runner::runner_of(&run.tool)?;
    let launch = runner::launch(target, rc, run);
    for n in &launch.notes {
        on_log(&format!("· {n}"));
    }
    let env = key_env(&run.tool, opts.key_id.as_deref())?;
    let env_names: Vec<String> = env.iter().map(|(k, _)| k.clone()).collect();
    if env.is_empty() {
        on_log("· no API key picked: the CLI inside has no login and will likely ask for one");
    }
    let image = ensure_image(&run.tool, on_log).await?;
    let dir = run_dir(id)?;
    let (work, base) = if opts.bind_original {
        (project.clone(), None)
    } else {
        on_log("· copying the project into the sandbox folder");
        let work = dir.join("work");
        if work.exists() {
            let _ = std::fs::remove_dir_all(&work);
        }
        let base = tree::copy_tree(&project, &work)?;
        (work, Some(base))
    };
    let name = format!(
        "omniget-sb-{}",
        id.chars()
            .filter(|c| c.is_ascii_alphanumeric())
            .collect::<String>()
    );
    let args = run_args(&name, &image, &work, &env_names, opts.network, &launch);
    let mut preview = vec!["docker".to_string()];
    preview.extend(args.iter().map(|a| {
        if a.len() > 120 {
            format!(
                "{}…",
                &a[..a.char_indices().nth(117).map(|(i, _)| i).unwrap_or(a.len())]
            )
        } else {
            a.clone()
        }
    }));
    let record = RunRecord {
        id: id.to_string(),
        provider: "docker".into(),
        tool: run.tool.clone(),
        project: project.clone(),
        work: work.clone(),
        bind_original: opts.bind_original,
        image: Some(image.clone()),
        env_names: env_names.clone(),
        argv_preview: preview,
        applied: vec![],
    };
    save_record(&dir, &record, base.as_ref())?;
    let spec = proc::Spawn {
        command: "docker".into(),
        args,
        env,
        env_remove: vec![],
        cwd: None,
    };
    let inner = CancellationToken::new();
    let watcher = {
        let (cancel, inner, name) = (cancel.clone(), inner.clone(), name.clone());
        tokio::spawn(async move {
            tokio::select! {
                _ = cancel.cancelled() => {
                    // The container outlives the docker client: stop it by name.
                    let _ = crate::core::process::command("docker").args(["kill", &name]).output().await;
                    inner.cancel();
                }
                _ = inner.cancelled() => {}
            }
        })
    };
    let out = runner::drive(spec, inner.clone(), on_log).await;
    inner.cancel();
    let _ = watcher.await;
    let mut out = out?;
    out.cancelled = cancel.is_cancelled();
    Ok((out, record))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn image_and_argv_never_carry_the_key_or_skip_permissions() {
        let df = dockerfile("claude").unwrap();
        assert!(
            df.contains("npm install -g @anthropic-ai/claude-code") && df.contains("USER node")
        );
        assert!(image_tag("claude", &df).starts_with("omniget-sandbox-claude:"));
        assert!(dockerfile("cursor").is_err());
        let (t, r) = runner::runner_of("claude").unwrap();
        let run = ToolRun {
            tool: "claude".into(),
            prompt: "go".into(),
            permission: runner::Permission::AcceptEdits,
            ..Default::default()
        };
        let l = runner::launch(t, r, &run);
        let a = run_args(
            "n",
            "img",
            Path::new("/tmp/w"),
            &["ANTHROPIC_API_KEY".into()],
            true,
            &l,
        );
        let joined = a.join(" ");
        assert!(joined.contains("-e ANTHROPIC_API_KEY img claude"));
        assert!(!joined.contains("dangerously"));
        assert!(!joined.contains("sk-"));
    }
}
