// Tauri sidecar preparation. No install, signing, upload or publication.
import { spawnSync } from 'node:child_process';
import { mkdirSync, copyFileSync, renameSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const cargoRoot = path.join(root, 'src-tauri');
const release = !process.argv.includes('--debug');
const rust = spawnSync('rustc', ['-vV'], { encoding: 'utf8' });
if (rust.status !== 0) throw new Error('Cannot determine Rust host target');
const triple = process.env.TAURI_ENV_TARGET_TRIPLE || rust.stdout.match(/^host: (.+)$/m)?.[1];
if (!triple || !/^[a-zA-Z0-9_-]+$/.test(triple)) throw new Error('Invalid Rust target');
if (triple === 'universal-apple-darwin') throw new Error('Build the worker separately for each macOS architecture');
const args = ['build', '--manifest-path', path.join(root, 'src-tauri/Cargo.toml'), '-p', 'omniget-cli', '--bin', 'omniget-worker', '--target', triple];
if (release) args.push('--release');
const metadata = spawnSync('cargo', ['metadata', '--no-deps', '--format-version', '1'], { cwd: cargoRoot, encoding: 'utf8' });
if (metadata.status !== 0) throw new Error('Cannot resolve Cargo target directory');
const target = JSON.parse(metadata.stdout).target_directory;
const result = spawnSync('cargo', args, { cwd: cargoRoot, stdio: 'inherit' });
if (result.status !== 0) process.exit(result.status || 1);
const ext = triple.includes('windows') ? '.exe' : '';
const source = path.join(target, triple, release ? 'release' : 'debug', `omniget-worker${ext}`);
const dest = path.join(root, 'src-tauri/binaries', `omniget-worker-${triple}${ext}`);
mkdirSync(path.dirname(dest), { recursive: true });
const pending = `${dest}.${process.pid}.pending`;
copyFileSync(source, pending);
renameSync(pending, dest);
console.log(`Prepared OmniGet worker for ${triple}`);
