//! Tools whose hooks are code: OpenCode and Kilo (JS plugin, `tool.execute.
//! before/after`, `event`, `chat.message`, `permission.ask`), Amp (TS plugin,
//! `amp.on('tool.call')`) and Pi (TS extension, `pi.on("tool_call")`). As
//! rulesync does, we generate one plugin file per component that shells out to
//! the hook command — through the shim, so the script receives Claude's JSON.

use serde_json::{json, Value};

use super::hook_common::{
    annotate, legacy_env_loss, missing, prepare, shim_note, shim_path, support_files, unit_name,
};
use super::{kind_path, ConvertCtx, PlannedFile};
use crate::core::agentkit::model::{Component, HookSpec};
use crate::core::agentkit::targets::TargetAdapter;
use crate::core::agentkit::{Env, Result, Scope};

/// One hook as the generated plugin sees it.
#[derive(Debug, Clone)]
pub struct PluginHook {
    pub event: String,
    pub native: String,
    pub matcher: Option<String>,
    pub command: String,
    pub timeout: Option<f64>,
}

impl PluginHook {
    fn to_json(&self) -> Value {
        json!({
            "event": self.event,
            "native": self.native,
            "matcher": self.matcher,
            "command": self.command,
            "timeout": self.timeout,
        })
    }
}

fn ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        s.insert(0, '_');
    }
    s
}

const RUNNER: &str = r#"function runHooks(native, payload) {
  const out = { decision: null, reason: "", context: [], updated_input: null, stop: false };
  for (const h of HOOKS) {
    if (h.native !== native) continue;
    const args = ["--tool", TOOL, "--event", h.event, "--native-event", native];
    if (h.matcher) args.push("--matcher", h.matcher);
    args.push("--", h.command);
    const body = JSON.stringify({ ...payload, hook_event_name: h.event });
    const r = spawnSync(SHIM, args, {
      input: body,
      encoding: "utf8",
      cwd: payload.cwd || process.cwd(),
      timeout: (h.timeout || 600) * 1000,
    });
    let res = {};
    try { res = JSON.parse(r.stdout || "{}") || {}; } catch (_) { res = {}; }
    if (r.status === 2) { res.decision = "deny"; res.reason = String(r.stderr || "").trim(); }
    if (res.context) out.context.push(res.context);
    if (res.updated_input) out.updated_input = Object.assign(out.updated_input || {}, res.updated_input);
    if (res.stop) out.stop = true;
    if (res.decision === "deny") { out.decision = "deny"; out.reason = res.reason || "Blocked by a hook"; break; }
    if (res.decision && !out.decision) out.decision = res.decision;
  }
  return out;
}
"#;

fn header(c_id: &str, name: &str, env: &Env, tool: &str, hooks: &[PluginHook]) -> String {
    let arr: Vec<Value> = hooks.iter().map(PluginHook::to_json).collect();
    format!(
        "// Generated by OmniGet (agentkit) from `{c_id}` ({name}). Reinstall or remove it from OmniGet.\n\
         // Runs the hook commands through omniget-hook-shim, which hands them Claude's hook JSON on stdin.\n\
         import {{ spawnSync }} from \"node:child_process\";\n\n\
         const SHIM = {};\n\
         const TOOL = {};\n\
         const HOOKS = {};\n\n{RUNNER}",
        json!(shim_path(env).display().to_string()),
        json!(tool),
        serde_json::to_string_pretty(&Value::Array(arr)).unwrap_or_else(|_| "[]".into()),
    )
}

fn has(hooks: &[PluginHook], native: &str) -> bool {
    hooks.iter().any(|h| h.native == native)
}

/// OpenCode / Kilo plugin body (the object of hook functions).
fn opencode_hooks(hooks: &[PluginHook]) -> String {
    let mut parts: Vec<String> = Vec::new();
    if has(hooks, "tool.execute.before") {
        parts.push(
            r#"    "tool.execute.before": async (input, output) => {
      const r = runHooks("tool.execute.before", {
        session_id: input.sessionID, cwd, tool_name: input.tool,
        tool_input: output.args || {}, tool_use_id: input.callID,
      });
      if (r.decision === "deny") throw new Error(r.reason);
      if (r.updated_input && output.args) Object.assign(output.args, r.updated_input);
    },"#
            .into(),
        );
    }
    if has(hooks, "tool.execute.after") {
        parts.push(
            r#"    "tool.execute.after": async (input, output) => {
      runHooks("tool.execute.after", {
        session_id: input.sessionID, cwd, tool_name: input.tool,
        tool_input: input.args || {}, tool_use_id: input.callID,
        tool_response: output && output.output,
      });
    },"#
            .into(),
        );
    }
    if has(hooks, "chat.message") {
        parts.push(
            r#"    "chat.message": async (input, output) => {
      const text = ((output && output.parts) || []).filter((p) => p.type === "text").map((p) => p.text).join("\n");
      const r = runHooks("chat.message", { session_id: input.sessionID, cwd, prompt: text });
      if (r.decision === "deny") throw new Error(r.reason);
    },"#
            .into(),
        );
    }
    if has(hooks, "permission.ask") {
        parts.push(
            r#"    "permission.ask": async (input, output) => {
      const r = runHooks("permission.ask", {
        session_id: input.sessionID, cwd, tool_name: input.type,
        tool_input: input.metadata || {}, message: input.title,
      });
      if (r.decision === "allow") output.status = "allow";
      else if (r.decision === "deny") output.status = "deny";
    },"#
            .into(),
        );
    }
    let bus: Vec<&str> = hooks
        .iter()
        .map(|h| h.native.as_str())
        .filter(|n| {
            !matches!(
                *n,
                "tool.execute.before" | "tool.execute.after" | "chat.message" | "permission.ask"
            )
        })
        .collect();
    if !bus.is_empty() {
        let mut uniq: Vec<&str> = Vec::new();
        for b in bus {
            if !uniq.contains(&b) {
                uniq.push(b);
            }
        }
        parts.push(format!(
            r#"    event: async ({{ event }}) => {{
      if (!event || !{}.includes(event.type)) return;
      const p = event.properties || {{}};
      runHooks(event.type, {{ session_id: p.sessionID || (p.info && p.info.id) || "", cwd, message: p.message }});
    }},"#,
            json!(uniq)
        ));
    }
    parts.join("\n")
}

fn opencode_file(c_id: &str, name: &str, env: &Env, tool: &str, hooks: &[PluginHook]) -> String {
    let id = ident(name);
    let body = opencode_hooks(hooks);
    let mut s = header(c_id, name, env, tool, hooks);
    s.push_str(&format!(
        "\nconst OmnigetHooks_{id} = async ({{ directory, worktree }}) => {{\n  const cwd = worktree || directory || process.cwd();\n  return {{\n{body}\n  }};\n}};\n\n"
    ));
    if tool == "kilo" {
        s.push_str(&format!(
            "export default {{ id: {}, server: OmnigetHooks_{id} }};\n",
            json!(format!("omniget-{name}"))
        ));
    } else {
        s.push_str(&format!("export {{ OmnigetHooks_{id} }};\n"));
    }
    s
}

fn amp_file(c_id: &str, name: &str, env: &Env, hooks: &[PluginHook]) -> String {
    let mut s = String::from("// @ts-nocheck\n");
    s.push_str(&header(c_id, name, env, "amp", hooks));
    s.push_str("\nexport default function (amp) {\n");
    if has(hooks, "tool.call") {
        s.push_str(
            r#"  amp.on("tool.call", async (event) => {
    const r = runHooks("tool.call", {
      session_id: (event.thread && event.thread.id) || "", cwd: process.cwd(),
      tool_name: event.tool, tool_input: event.input || {}, tool_use_id: event.toolUseID,
    });
    if (r.decision === "deny") return { action: "reject-and-continue", message: r.reason };
    if (r.updated_input) return { action: "modify", input: { ...(event.input || {}), ...r.updated_input } };
    return { action: "allow" };
  });
"#,
        );
    }
    for (native, extra) in [
        (
            "tool.result",
            "tool_name: event.tool, tool_input: event.input || {}, tool_response: event.output, ",
        ),
        ("session.start", ""),
        ("agent.start", ""),
        ("agent.end", ""),
    ] {
        if has(hooks, native) {
            s.push_str(&format!(
                "  amp.on({n}, async (event) => {{\n    runHooks({n}, {{ session_id: (event && event.thread && event.thread.id) || \"\", cwd: process.cwd(), {extra}}});\n  }});\n",
                n = json!(native)
            ));
        }
    }
    s.push_str("}\n");
    s
}

fn pi_file(c_id: &str, name: &str, env: &Env, hooks: &[PluginHook]) -> String {
    let mut s = String::from("// @ts-nocheck\n");
    s.push_str(&header(c_id, name, env, "pi", hooks));
    s.push_str("\nexport default function (pi) {\n");
    if has(hooks, "tool_call") {
        s.push_str(
            r#"  pi.on("tool_call", async (event, ctx) => {
    const r = runHooks("tool_call", {
      session_id: (ctx && ctx.sessionId) || "", cwd: (ctx && ctx.cwd) || process.cwd(),
      tool_name: event.toolName, tool_input: event.input || {}, tool_use_id: event.toolCallId,
    });
    if (r.decision === "deny") return { block: true, reason: r.reason };
    if (r.updated_input && event.input) Object.assign(event.input, r.updated_input);
  });
"#,
        );
    }
    if has(hooks, "input") {
        s.push_str(
            r#"  pi.on("input", async (event, ctx) => {
    const r = runHooks("input", { session_id: (ctx && ctx.sessionId) || "", cwd: (ctx && ctx.cwd) || process.cwd(), prompt: event.text });
    if (r.decision === "deny") return { action: "handled" };
  });
"#,
        );
    }
    for (native, extra) in [
        ("tool_result", "tool_name: event.toolName, tool_input: event.input || {}, tool_response: event.content, "),
        ("session_start", ""),
        ("session_shutdown", ""),
        ("agent_end", ""),
        ("session_before_compact", ""),
    ] {
        if has(hooks, native) {
            s.push_str(&format!(
                "  pi.on({n}, async (event, ctx) => {{\n    runHooks({n}, {{ session_id: (ctx && ctx.sessionId) || \"\", cwd: (ctx && ctx.cwd) || process.cwd(), {extra}}});\n  }});\n",
                n = json!(native)
            ));
        }
    }
    s.push_str("}\n");
    s
}

/// The generated file (name, text) for one tool.
pub fn render(
    tool: &str,
    c_id: &str,
    name: &str,
    env: &Env,
    hooks: &[PluginHook],
) -> (String, String) {
    match tool {
        "amp" => (
            format!("omniget-{name}.ts"),
            amp_file(c_id, name, env, hooks),
        ),
        "pi" => (
            format!("omniget-{name}.ts"),
            pi_file(c_id, name, env, hooks),
        ),
        _ => (
            format!("omniget-{name}.js"),
            opencode_file(c_id, name, env, tool, hooks),
        ),
    }
}

/// Plugin hooks from prepared entries: the matcher always goes to the shim
/// (the plugin sees native tool names, the shim compares Claude's).
pub fn plugin_hooks(prep: &[super::hook_common::Prepared]) -> Vec<PluginHook> {
    let mut out = Vec::new();
    for p in prep {
        for native in &p.natives {
            out.push(PluginHook {
                event: p.event.clone(),
                native: native.clone(),
                matcher: p.matcher.clone(),
                command: p.command.clone(),
                timeout: p.timeout,
            });
        }
    }
    out
}

fn tool_losses(tool: &str, prep: &[super::hook_common::Prepared]) -> Vec<String> {
    let mut out = Vec::new();
    for p in prep {
        let l = match (tool, p.event.as_str()) {
            (
                "opencode" | "kilo",
                "Stop" | "SessionEnd" | "SessionStart" | "PreCompact" | "Notification",
            ) => Some(format!(
                "{}: runs on the {} bus event, cannot block or add context",
                p.event, tool
            )),
            ("opencode" | "kilo", "PostToolUse") => {
                Some("PostToolUse: additional context and blocking are ignored".to_string())
            }
            ("amp", "Stop" | "SessionStart" | "PostToolUse") => {
                Some(format!("{}: observe only in Amp", p.event))
            }
            ("pi", e) if e != "PreToolUse" && e != "UserPromptSubmit" => {
                Some(format!("{e}: observe only in Pi"))
            }
            _ => None,
        };
        if let Some(l) = l {
            if !out.contains(&l) {
                out.push(l);
            }
        }
    }
    out
}

pub fn code_plugin(
    c: &Component,
    h: &HookSpec,
    target: &TargetAdapter,
    scope: Scope,
    ctx: &ConvertCtx,
) -> Result<Vec<PlannedFile>> {
    let dir = kind_path(target, "hooks", scope, ctx)
        .ok_or_else(|| missing(target, "plugins folder", scope))?;
    let (support, rewrites) = support_files(c, h, target, scope, ctx)?;
    let (prep, mut losses, commands) = prepare(h, target, &rewrites, &[]);
    losses.extend(tool_losses(&target.id, &prep));
    if let Some(l) = legacy_env_loss(c) {
        losses.push(l);
    }
    let hooks = plugin_hooks(&prep);
    let mut files = Vec::new();
    if !hooks.is_empty() {
        let name = unit_name(c, ctx);
        let (fname, text) = render(&target.id, &c.id, &name, ctx.env, &hooks);
        let mut pf = PlannedFile::write(&target.id, c, dir.join(fname), text, "hook plugin");
        pf.primary = true;
        if target.id == "pi" || target.id == "amp" {
            pf.notes.push(format!(
                "the {} event API shape is taken from the docs and was not run here",
                target.name
            ));
        }
        files.push(pf);
    }
    annotate(&mut files, losses, commands, Some(shim_note(ctx.env)));
    files.extend(support);
    Ok(files)
}
