//! Cline: one executable per event (`.clinerules/hooks/PreToolUse`, or
//! `PreToolUse.ps1` on Windows). Several components can hook the same event, so
//! the file is a small dispatcher (the same bytes for everyone) that hands the
//! payload to the shim, and the hooks themselves live in a registry of
//! Claude-shaped groups keyed by Cline event (`.omniget/cline-hooks.json` in the
//! project, `<app_data>/agentkit/cline-hooks.json` globally), merged per
//! component so install/uninstall stay exact.

use std::path::{Path, PathBuf};

use serde_json::{json, Map, Value};

use super::hook_common::{
    annotate, legacy_env_loss, missing, num, prepare, ps_quote, quote, shim_path, support_files,
};
use super::{kind_path, ConvertCtx, Dedupe, PatchOp, PlannedFile};
use crate::core::agentkit::edit::{keys, DocFormat};
use crate::core::agentkit::model::{Component, HookSpec};
use crate::core::agentkit::targets::TargetAdapter;
use crate::core::agentkit::{Os, Result, Scope};

pub const REGISTRY_FILE: &str = "cline-hooks.json";

/// Where the registry lives for a scope.
pub fn registry_path(scope: Scope, ctx: &ConvertCtx) -> Option<PathBuf> {
    match scope {
        Scope::Project | Scope::Local => Some(ctx.project?.join(".omniget").join(REGISTRY_FILE)),
        _ => Some(ctx.env.agentkit_dir().join(REGISTRY_FILE)),
    }
}

/// `"$(dirname "$0")/../../.omniget/cline-hooks.json"` style reference from the
/// hooks dir to the project registry, so the project can move.
fn relative_up(hooks_dir: &Path, project: &Path) -> Option<String> {
    let rel = hooks_dir.strip_prefix(project).ok()?;
    let depth = rel.components().count();
    Some("../".repeat(depth))
}

fn dispatcher(
    ctx: &ConvertCtx,
    native: &str,
    hooks_dir: &Path,
    registry: &Path,
    project_bound: bool,
) -> (String, String) {
    let os = ctx.env.os;
    let shim = shim_path(ctx.env).display().to_string();
    let up = if project_bound {
        ctx.project.and_then(|p| relative_up(hooks_dir, p))
    } else {
        None
    };
    if os == Os::Windows {
        let reg = match &up {
            Some(u) => format!(
                "(Join-Path $PSScriptRoot {})",
                ps_quote(&format!("{u}.omniget/{REGISTRY_FILE}").replace('/', "\\"))
            ),
            None => ps_quote(&registry.display().to_string()),
        };
        let text = format!(
            "# Generated by OmniGet (agentkit): runs the hooks registered for this Cline event.\r\n\
             $payload = [Console]::In.ReadToEnd()\r\n\
             $payload | & {} '--tool' 'cline' '--native-event' {} '--dispatch' {}\r\n\
             exit $LASTEXITCODE\r\n",
            ps_quote(&shim),
            ps_quote(native),
            reg
        );
        (format!("{native}.ps1"), text)
    } else {
        let reg = match &up {
            Some(u) => format!("\"$(dirname \"$0\")/{u}.omniget/{REGISTRY_FILE}\""),
            None => quote(&registry.display().to_string(), os),
        };
        let text = format!(
            "#!/bin/sh\n\
             # Generated by OmniGet (agentkit): runs the hooks registered for this Cline event.\n\
             exec {} --tool cline --native-event {} --dispatch {}\n",
            quote(&shim, os),
            quote(native, os),
            reg
        );
        (native.to_string(), text)
    }
}

pub fn cline(
    c: &Component,
    h: &HookSpec,
    target: &TargetAdapter,
    scope: Scope,
    ctx: &ConvertCtx,
) -> Result<Vec<PlannedFile>> {
    let hooks_dir = kind_path(target, "hooks", scope, ctx)
        .ok_or_else(|| missing(target, "hooks folder", scope))?;
    let registry = registry_path(scope, ctx).ok_or_else(|| missing(target, "project", scope))?;
    let (support, rewrites) = support_files(c, h, target, scope, ctx)?;
    let (prep, mut losses, commands) = prepare(h, target, &rewrites, &[]);
    let mut ops = Vec::new();
    let mut natives_used: Vec<String> = Vec::new();
    for p in &prep {
        for native in &p.natives {
            let mut hk = Map::new();
            hk.insert("type".into(), json!("command"));
            hk.insert("command".into(), json!(p.command));
            hk.insert("event".into(), json!(p.event));
            if let Some(t) = p.timeout {
                hk.insert("timeout".into(), num(t));
            }
            let mut g = Map::new();
            if let Some(m) = &p.matcher {
                // canonical matcher: the shim compares Claude tool names
                g.insert("matcher".into(), json!(m));
            }
            g.insert("hooks".into(), json!([Value::Object(hk)]));
            ops.push(PatchOp::Append {
                path: keys(["hooks", native.as_str()]),
                value: Value::Object(g),
                dedupe: Dedupe::ClaudeHook,
            });
            if !natives_used.contains(native) {
                natives_used.push(native.clone());
            }
        }
        if p.timeout.map(|t| t > 30.0).unwrap_or(false) {
            let l = "hook timeouts over 30 s (Cline VS Code stops hooks at 30 s)".to_string();
            if !losses.contains(&l) {
                losses.push(l);
            }
        }
    }
    let mut files = Vec::new();
    if !ops.is_empty() {
        let mut reg = PlannedFile::merge(
            &target.id,
            c,
            registry.clone(),
            DocFormat::Json,
            ops,
            "hook",
        );
        reg.notes
            .push("VS Code: turn on \"Enable Hooks\" in Cline's Feature Settings".into());
        files.push(reg);
        for native in natives_used {
            let (fname, text) = dispatcher(
                ctx,
                &native,
                &hooks_dir,
                &registry,
                scope.is_project_bound(),
            );
            let mut pf = PlannedFile::write(
                &target.id,
                c,
                hooks_dir.join(fname),
                text,
                "hook dispatcher",
            );
            pf.executable = true;
            files.push(pf);
        }
    }
    if let Some(l) = legacy_env_loss(c) {
        losses.push(l);
    }
    annotate(
        &mut files,
        losses,
        commands,
        Some(super::hook_common::shim_note(ctx.env)),
    );
    files.extend(support);
    Ok(files)
}
