pub mod auth;
pub mod events;
pub mod http_client;
pub use omniget_core::core::registry;
pub mod hls_downloader;
pub mod direct_downloader;
pub mod redirect;
pub mod filename;
pub mod url_parser;
pub mod queue;

#[cfg(not(target_os = "android"))]
pub mod process;
#[cfg(not(target_os = "android"))]
pub mod ffmpeg;
#[cfg(not(target_os = "android"))]
pub mod hwaccel;
#[cfg(not(target_os = "android"))]
pub mod media_processor;
#[cfg(not(target_os = "android"))]
pub mod ytdlp;
#[cfg(not(target_os = "android"))]
pub mod dependencies;
