//! Localhost HTTP bridge between the browser extension and the desktop app.
//!
//! Replaces the previous Chrome native-messaging path, which required
//! hard-coding extension IDs in an OS-installed manifest. This bridge listens
//! on `127.0.0.1:<port>` and authenticates extension requests with a single
//! random token that the user pairs once via the app's settings UI.
//!
//! The token is regenerated by hand from the settings (or by deleting it from
//! `settings.json`); the port is picked at first launch from a small range
//! and persisted so the extension always knows where to connect.
//!
//! Endpoints:
//!
//! * `GET  /v1/health`  — unauthenticated; returns `{ ok, version }` so the
//!                         extension can detect that the app is running.
//! * `POST /v1/enqueue` — authenticated; same payload as the legacy native
//!                         host accepted (`ExtensionPayload`). Validates the
//!                         URL, writes cookies + metadata to disk, then queues
//!                         the URL through `external_url::handle_external_url`.

use std::net::SocketAddr;
use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::Arc;

use axum::{
    extract::DefaultBodyLimit,
    extract::State,
    http::{HeaderMap, Method, StatusCode},
    response::{IntoResponse, Response},
    routing::{get, post},
    Json, Router,
};
use base64::Engine;
use serde::{Deserialize, Serialize};
use socket2::{Domain, Protocol, Socket, Type};
use tauri::{AppHandle, Emitter};
use tokio::net::TcpListener;
use tower_http::cors::{Any, CorsLayer};

use crate::extension_storage::{
    cookie_limit, write_extension_metadata, ExtensionCookie, ExtensionPayload,
};
use crate::storage::config;
use tauri::Manager;

/// Range of ports we'll try when picking a fresh `bridge.port`. Chosen above
/// the most common dev-server / Vite ranges so collisions are rare.
const PORT_RANGE: std::ops::Range<u16> = 47720..47730;

#[derive(Clone)]
pub struct BridgeState {
    pub app: AppHandle,
    /// Authoritative copy of the bearer token, kept in `Arc` so cloning the
    /// state for each handler doesn't allocate, and so reading it is lock-free.
    pub token: Arc<String>,
}

#[derive(Debug, Serialize)]
struct HealthResponse {
    ok: bool,
    version: &'static str,
}

#[derive(Debug, Serialize)]
struct EnqueueResponse {
    ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    code: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    message: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EnqueueRequest {
    #[serde(flatten)]
    payload: ExtensionPayload,
    #[serde(default)]
    protocol_version: Option<u32>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CookiesRequest {
    #[serde(default)]
    cookies: Vec<ExtensionCookie>,
    #[serde(default)]
    protocol_version: Option<u32>,
    #[serde(default)]
    source_url: Option<String>,
    #[serde(default)]
    page_title: Option<String>,
    #[serde(default)]
    alias: Option<String>,
}

const HOST_MAX_PROTOCOL_VERSION: u32 = 1;

/// Body cap for `/v1/enqueue`, kept a little above the extension's own 4 MiB
/// ceiling on the manifest text so the payload's metadata and cookies fit too.
const ENQUEUE_BODY_LIMIT: usize = 8 * 1024 * 1024;

/// Generate a random bearer token (32 bytes, URL-safe base64, no padding).
pub fn generate_token() -> String {
    let mut buf = [0u8; 32];
    rand::Rng::fill_bytes(&mut rand::rng(), &mut buf);
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(buf)
}

/// Bind a TCP listener on `127.0.0.1:port` with `SO_REUSEADDR` enabled so
/// the port can be re-bound immediately across app restarts (the previous
/// socket stays in `TIME_WAIT` for ~60 s otherwise, which would otherwise
/// kick us off our persisted port and force re-pairing).
fn bind_with_reuse(port: u16) -> std::io::Result<TcpListener> {
    let addr: SocketAddr = ([127, 0, 0, 1], port).into();
    let socket = Socket::new(Domain::IPV4, Type::STREAM, Some(Protocol::TCP))?;
    socket.set_reuse_address(true)?;
    socket.set_nonblocking(true)?;
    socket.bind(&addr.into())?;
    socket.listen(128)?;
    let std_listener: std::net::TcpListener = socket.into();
    TcpListener::from_std(std_listener)
}

/// Try to bind a free TCP listener — first the persisted port, then the
/// preferred range, finally `0` (OS-picked) as last resort.
async fn bind_listener(preferred: u16) -> std::io::Result<(u16, TcpListener)> {
    if preferred != 0 {
        if let Ok(listener) = bind_with_reuse(preferred) {
            return Ok((preferred, listener));
        }
    }

    for port in PORT_RANGE {
        if let Ok(listener) = bind_with_reuse(port) {
            return Ok((port, listener));
        }
    }

    let listener = bind_with_reuse(0)?;
    let port = listener.local_addr()?.port();
    Ok((port, listener))
}

/// Ensure `settings.bridge.{token,port}` are populated and persisted.
/// Returns the resolved (token, port) pair to use for this run.
fn ensure_bridge_settings(app: &AppHandle, bound_port: u16) -> anyhow::Result<(String, u16)> {
    let mut settings = config::load_settings(app);
    let mut dirty = false;

    if settings.bridge.token.trim().is_empty() {
        settings.bridge.token = generate_token();
        dirty = true;
    }
    if settings.bridge.port != bound_port {
        settings.bridge.port = bound_port;
        dirty = true;
    }

    if dirty {
        config::save_settings(app, &settings)?;
    }

    Ok((settings.bridge.token, settings.bridge.port))
}

/// Spawn the localhost bridge in a background tokio task.
///
/// Returns once the listener has been bound (so the port is known and
/// persisted), then continues serving on the spawned task. Errors during
/// binding are logged but never propagated up — the deep-link path remains
/// usable as a fallback.
pub async fn spawn(app: AppHandle) {
    let settings = config::load_settings(&app);

    if !settings.bridge.enabled {
        tracing::info!("local bridge disabled by settings; not starting HTTP server");
        return;
    }

    let preferred_port = settings.bridge.port;
    let (port, listener) = match bind_listener(preferred_port).await {
        Ok(pair) => pair,
        Err(error) => {
            tracing::warn!(
                "failed to bind local bridge on 127.0.0.1: {} — extension cookie path disabled",
                error
            );
            return;
        }
    };

    let (token, _port) = match ensure_bridge_settings(&app, port) {
        Ok(pair) => pair,
        Err(error) => {
            tracing::warn!("failed to persist bridge settings: {}", error);
            return;
        }
    };

    let state = BridgeState {
        app: app.clone(),
        token: Arc::new(token),
    };

    let cors = CorsLayer::new()
        // The token is the actual auth boundary, so we accept any browser
        // origin (extension or webpage). Requests without a valid bearer are
        // still rejected by the handler.
        .allow_origin(Any)
        .allow_methods([Method::GET, Method::POST, Method::OPTIONS])
        .allow_headers(Any);

    let router = Router::new()
        .route("/v1/health", get(health))
        .route("/v1/pair", get(pair))
        .route(
            "/v1/enqueue",
            // The extension may attach the full text of a captured HLS playlist
            // (`manifestText`), which it caps at 4 MiB. Axum's default cap is
            // 2 MiB, and hitting it fails the whole enqueue with a 413 — the
            // download would not merely lose its manifest, it would never be
            // queued at all.
            post(enqueue).layer(DefaultBodyLimit::max(ENQUEUE_BODY_LIMIT)),
        )
        .route("/v1/queue", get(queue_state))
        .route("/v1/log/{id}", get(download_log))
        .route("/v1/cookies", post(cookies_export))
        .route("/mcp", post(mcp_post).get(mcp_get).delete(mcp_get))
        .route("/mcp/artifacts/{id}", get(mcp_artifact))
        // Scoped projection of the assistant tools for CLI/ACP runtimes: its
        // own bearer (a per-session token), never the extension's.
        .route(
            "/mcp/assist",
            post(assist_mcp_post).get(mcp_get).delete(mcp_get),
        )
        .merge(crate::local_bridge_llm::router(
            crate::local_bridge_llm::LlmBridgeState::from_bridge(&state),
        ))
        .merge(crate::local_bridge_jobs::router(
            crate::local_bridge_jobs::JobsBridgeState::from_bridge(&state),
        ))
        .merge(crate::local_bridge_debug::router(
            state.app.clone(),
            state.token.clone(),
        ))
        .with_state(state)
        .layer(cors);

    tracing::info!("local bridge listening on http://127.0.0.1:{port}");
    omniget_core::core::assist::projection::set_endpoint(Some(format!(
        "http://127.0.0.1:{port}/mcp/assist"
    )));

    tokio::spawn(async move {
        if let Err(error) = axum::serve(listener, router).await {
            tracing::warn!("local bridge stopped: {error}");
        }
    });
}

/// Estado da fila, o mesmo `QueueItemInfo` que a tela recebe. Serve para a
/// extensão mostrar progresso e para harness de teste observar o app por
/// fora sem instrumentar a UI. Mesmo bearer do `enqueue`.
async fn queue_state(State(state): State<BridgeState>, headers: HeaderMap) -> Response {
    if !check_bearer(&headers, &state.token) {
        return unauthorized();
    }
    let app_state = state.app.state::<crate::AppState>();
    let items = {
        let q = app_state.download_queue.lock().await;
        q.get_state()
    };
    let items = crate::core::queue::redacted_for_display(items);
    (StatusCode::OK, Json(items)).into_response()
}

/// Últimas linhas do log de um download (até 200, redigidas na origem).
async fn download_log(
    State(state): State<BridgeState>,
    headers: HeaderMap,
    axum::extract::Path(id): axum::extract::Path<u64>,
) -> Response {
    if !check_bearer(&headers, &state.token) {
        return unauthorized();
    }
    let lines = crate::core::download_log::get(id);
    (StatusCode::OK, Json(lines)).into_response()
}

async fn health() -> Json<HealthResponse> {
    Json(HealthResponse {
        ok: true,
        version: env!("CARGO_PKG_VERSION"),
    })
}

/// Seconds the pairing window stays open after the user clicks "Pair" in the
/// app. The window is single-use (closed on the first successful hand-out).
pub const PAIR_WINDOW_SECS: i64 = 120;

/// Unix-ms deadline until which `GET /v1/pair` will return the token.
/// `0` means the pairing window is closed.
static PAIR_OPEN_UNTIL_MS: AtomicI64 = AtomicI64::new(0);

fn now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// Opens the user-consented pairing window. Returns the window length (s).
pub fn open_pairing_window() -> i64 {
    PAIR_OPEN_UNTIL_MS.store(now_ms() + PAIR_WINDOW_SECS * 1000, Ordering::SeqCst);
    PAIR_WINDOW_SECS
}

fn pairing_open() -> bool {
    PAIR_OPEN_UNTIL_MS.load(Ordering::SeqCst) > now_ms()
}

#[derive(Debug, Serialize)]
struct PairResponse {
    ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    token: Option<String>,
}

async fn pair(State(state): State<BridgeState>, headers: HeaderMap) -> Response {
    if !pairing_open() {
        return (
            StatusCode::FORBIDDEN,
            Json(PairResponse {
                ok: false,
                token: None,
            }),
        )
            .into_response();
    }
    PAIR_OPEN_UNTIL_MS.store(0, Ordering::SeqCst);
    tracing::info!("[bridge] pairing token handed out (window closed, single-use)");

    // Tell the Settings UI that pairing actually succeeded, so it can flip
    // from the countdown to a success state instead of silently expiring.
    let user_agent = headers
        .get("user-agent")
        .and_then(|v| v.to_str().ok())
        .map(str::to_string);
    if let Err(error) = state.app.emit(
        "bridge-paired",
        serde_json::json!({ "userAgent": user_agent }),
    ) {
        tracing::warn!("[bridge] failed to emit bridge-paired event: {error}");
    }

    (
        StatusCode::OK,
        Json(PairResponse {
            ok: true,
            token: Some((*state.token).clone()),
        }),
    )
        .into_response()
}

fn unauthorized() -> Response {
    let body = Json(EnqueueResponse {
        ok: false,
        code: Some("UNAUTHORIZED"),
        message: Some("Invalid or missing bearer token".to_string()),
    });
    (StatusCode::UNAUTHORIZED, body).into_response()
}

fn check_bearer(headers: &HeaderMap, expected: &str) -> bool {
    let header = match headers.get("authorization") {
        Some(v) => v,
        None => return false,
    };
    let raw = match header.to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    let provided = match raw
        .strip_prefix("Bearer ")
        .or_else(|| raw.strip_prefix("bearer "))
    {
        Some(s) => s.trim(),
        None => return false,
    };
    constant_time_eq::constant_time_eq(provided.as_bytes(), expected.as_bytes())
}

async fn enqueue(
    State(state): State<BridgeState>,
    headers: HeaderMap,
    Json(request): Json<EnqueueRequest>,
) -> Response {
    if !check_bearer(&headers, &state.token) {
        return unauthorized();
    }

    if let Some(client_version) = request.protocol_version {
        if client_version > HOST_MAX_PROTOCOL_VERSION {
            return error_response(
                StatusCode::BAD_REQUEST,
                "UNSUPPORTED_PROTOCOL",
                format!(
                    "Extension protocol v{client_version} is newer than host v{HOST_MAX_PROTOCOL_VERSION}. Please update OmniGet."
                ),
            );
        }
    }

    let payload = request.payload;

    if !crate::external_url::is_external_url(&payload.url) {
        return error_response(
            StatusCode::BAD_REQUEST,
            "INVALID_URL",
            "The requested URL is invalid".to_string(),
        );
    }

    if let Some(ref cookies) = payload.cookies {
        if cookies.len() > cookie_limit() {
            return error_response(
                StatusCode::BAD_REQUEST,
                "TOO_MANY_COOKIES",
                format!(
                    "Request contains {} cookies; max allowed is {}",
                    cookies.len(),
                    cookie_limit()
                ),
            );
        }
        if !cookies.is_empty() {
            if let Err(error) = crate::cookies::ingest_batch(
                cookies,
                crate::cookies::IngestSource {
                    source_url: payload
                        .page_url
                        .clone()
                        .or_else(|| Some(payload.url.clone())),
                    source_label: "Browser extension".to_string(),
                    alias_hint: payload.title.clone(),
                },
            ) {
                tracing::warn!("failed to ingest cookies into manager: {error}");
            }
        }
    }

    if payload.referer.is_some()
        || payload.headers.is_some()
        || payload.media_type.is_some()
        || payload.title.is_some()
        || payload.thumbnail.is_some()
        || payload.open_app.is_some()
        || payload.page_url.is_some()
        || payload.user_agent.is_some()
    {
        if let Err(error) = write_extension_metadata(&payload) {
            tracing::warn!("failed to write extension metadata: {error}");
        }
    }

    // Deep search can recover an HLS playlist that only ever existed as a
    // `blob:` URL inside the tab, so the extension ships its text instead of
    // an address. Park it on disk keyed by URL; the HLS downloader picks it
    // up when the item finally leaves the queue. A failure here only costs us
    // the shortcut, never the enqueue.
    if let Some(text) = payload.manifest_text.as_deref() {
        if !text.trim().is_empty() {
            match omniget_core::core::extension_manifest::store_manifest(&payload.url, text) {
                Ok(()) => tracing::info!(
                    "stored extension-captured playlist ({} bytes) for {}",
                    text.len(),
                    payload.url
                ),
                Err(error) => {
                    tracing::warn!("failed to store extension playlist text: {error}")
                }
            }
        }
    }

    let app = state.app.clone();
    let url = payload.url.clone();
    tauri::async_runtime::spawn(async move {
        if let Err(error) = crate::external_url::handle_external_url(&app, url, "bridge").await {
            tracing::warn!("failed to handle bridge URL: {error}");
        }
    });

    let body = Json(EnqueueResponse {
        ok: true,
        code: None,
        message: None,
    });
    (StatusCode::OK, body).into_response()
}

async fn cookies_export(
    State(state): State<BridgeState>,
    headers: HeaderMap,
    Json(request): Json<CookiesRequest>,
) -> Response {
    if !check_bearer(&headers, &state.token) {
        return unauthorized();
    }

    if let Some(client_version) = request.protocol_version {
        if client_version > HOST_MAX_PROTOCOL_VERSION {
            return error_response(
                StatusCode::BAD_REQUEST,
                "UNSUPPORTED_PROTOCOL",
                format!(
                    "Extension protocol v{client_version} is newer than host v{HOST_MAX_PROTOCOL_VERSION}. Please update OmniGet."
                ),
            );
        }
    }

    if request.cookies.len() > cookie_limit() {
        return error_response(
            StatusCode::BAD_REQUEST,
            "TOO_MANY_COOKIES",
            format!(
                "cookies:export contains {} cookies; max is {}",
                request.cookies.len(),
                cookie_limit()
            ),
        );
    }

    if !request.cookies.is_empty() {
        let label = if request.source_url.is_some() || request.alias.is_some() {
            "Browser extension (manual capture)".to_string()
        } else {
            "Browser extension (auto-capture)".to_string()
        };
        let alias_hint = request.alias.clone().or_else(|| request.page_title.clone());
        if let Err(error) = crate::cookies::ingest_batch(
            &request.cookies,
            crate::cookies::IngestSource {
                source_url: request.source_url.clone(),
                source_label: label,
                alias_hint,
            },
        ) {
            return error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                "WRITE_FAILED",
                format!("ingest cookies: {error}"),
            );
        }
    }

    let body = Json(EnqueueResponse {
        ok: true,
        code: None,
        message: None,
    });
    (StatusCode::OK, body).into_response()
}

fn error_response(status: StatusCode, code: &'static str, message: String) -> Response {
    let body = Json(EnqueueResponse {
        ok: false,
        code: Some(code),
        message: Some(message),
    });
    (status, body).into_response()
}

pub fn build_pairing_url(port: u16) -> String {
    format!("http://127.0.0.1:{port}")
}

// ── MCP (Streamable HTTP, só JSON) ─────────────────────────────────────

/// `POST /mcp`: JSON-RPC do MCP. Mesmo bearer da extensão; 403 quando a
/// tool "Servidor MCP" está desligada; 202 sem corpo para notificações.
async fn mcp_post(
    State(state): State<BridgeState>,
    headers: HeaderMap,
    body: axum::body::Bytes,
) -> Response {
    let principal =
        match bearer_of(&headers).and_then(|t| crate::mcp::policy::authenticate(&t).ok()) {
            Some(p) => p,
            None => return unauthorized(),
        };
    let host = headers
        .get("host")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");
    let valid_host = url::Url::parse(&format!("http://{host}"))
        .ok()
        .is_some_and(|u| {
            matches!(u.host_str(), Some("127.0.0.1" | "localhost" | "[::1]"))
                && u.username().is_empty()
                && u.path() == "/"
        });
    if !valid_host || headers.contains_key("origin") {
        return (
            StatusCode::FORBIDDEN,
            "MCP accepts authenticated native clients only",
        )
            .into_response();
    }
    if headers
        .get("mcp-protocol-version")
        .is_some_and(|v| !matches!(v.to_str(), Ok("2025-03-26" | "2025-06-18")))
    {
        return (StatusCode::BAD_REQUEST, "Unsupported MCP protocol version").into_response();
    }
    if !headers
        .get("content-type")
        .and_then(|h| h.to_str().ok())
        .is_some_and(|s| s.split(';').next() == Some("application/json"))
    {
        return StatusCode::UNSUPPORTED_MEDIA_TYPE.into_response();
    }
    if body.len() > 65536 {
        return StatusCode::PAYLOAD_TOO_LARGE.into_response();
    }
    let accept = headers
        .get("accept")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");
    if !accept.contains("application/json") || !accept.contains("text/event-stream") {
        return StatusCode::NOT_ACCEPTABLE.into_response();
    }

    if !crate::mcp::enabled() {
        return (StatusCode::FORBIDDEN, Json(serde_json::json!({ "error": "MCP server is disabled in OmniGet → Tools → MCP server" }))).into_response();
    }
    let msg: serde_json::Value = match serde_json::from_slice(&body) {
        Ok(v) => v,
        Err(e) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(serde_json::json!({ "jsonrpc": "2.0", "id": null, "error": { "code": -32700, "message": format!("parse error: {}", e) } })),
            )
                .into_response()
        }
    };
    let protocol = headers
        .get("mcp-protocol-version")
        .and_then(|v| v.to_str().ok())
        .map(str::to_owned);
    match crate::mcp::REQUEST_PROTOCOL
        .scope(
            protocol,
            crate::mcp::handle_body(&state.app, &principal, &msg),
        )
        .await
    {
        Some(resp) => (StatusCode::OK, Json(resp)).into_response(),
        None => StatusCode::ACCEPTED.into_response(),
    }
}

fn bearer_of(headers: &HeaderMap) -> Option<String> {
    let raw = headers.get("authorization")?.to_str().ok()?;
    raw.strip_prefix("Bearer ")
        .or_else(|| raw.strip_prefix("bearer "))
        .map(|s| s.trim().to_string())
}

/// Authorized byte transport, separate from JSON-RPC. Each 64 KiB chunk
/// rechecks revocation/expiry. Bytes already in socket buffers cannot be recalled.
async fn mcp_artifact(
    axum::extract::Path(id): axum::extract::Path<String>,
    headers: HeaderMap,
) -> Response {
    use tokio::io::{AsyncReadExt, AsyncSeekExt};
    if !crate::mcp::enabled() {
        return StatusCode::FORBIDDEN.into_response();
    }
    let principal =
        match bearer_of(&headers).and_then(|t| crate::mcp::policy::authenticate(&t).ok()) {
            Some(p) => p,
            None => return unauthorized(),
        };
    let host = headers
        .get("host")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");
    if headers.contains_key("origin")
        || !url::Url::parse(&format!("http://{host}"))
            .ok()
            .is_some_and(|u| {
                matches!(u.host_str(), Some("127.0.0.1" | "localhost" | "[::1]"))
                    && u.username().is_empty()
                    && u.path() == "/"
            })
    {
        return StatusCode::FORBIDDEN.into_response();
    }
    let Some(digest) = headers
        .get("if-match")
        .and_then(|v| v.to_str().ok())
        .map(|v| v.trim_matches('"').to_owned())
    else {
        return StatusCode::PRECONDITION_REQUIRED.into_response();
    };
    let (_, last) = match crate::mcp::artifacts::preflight(&principal, &id, &digest, None) {
        Ok(size) => size,
        Err(e) if e == "ARTIFACT_REVISION_MISMATCH" => {
            return StatusCode::PRECONDITION_FAILED.into_response()
        }
        _ => return StatusCode::NOT_FOUND.into_response(),
    };
    if crate::mcp::artifacts::range(headers.get("range").and_then(|v| v.to_str().ok()), last + 1)
        .is_err()
    {
        return (
            StatusCode::RANGE_NOT_SATISFIABLE,
            [("content-range", format!("bytes */{}", last + 1))],
        )
            .into_response();
    }
    let permit = match crate::mcp::artifacts::admit() {
        Ok(p) => p,
        Err(_) => return StatusCode::TOO_MANY_REQUESTS.into_response(),
    };
    let p = principal.clone();
    let aid = id.clone();
    let (snapshot, permit) = match tokio::task::spawn_blocking(move || {
        crate::mcp::artifacts::open(&p, &aid, &digest).map(|s| (s, permit))
    })
    .await
    {
        Ok(Ok(s)) => s,
        Ok(Err(e)) if e == "ARTIFACT_REVISION_MISMATCH" => {
            return StatusCode::PRECONDITION_FAILED.into_response()
        }
        _ => return StatusCode::NOT_FOUND.into_response(),
    };
    let bytes = snapshot.bytes;
    let (start, end) = match crate::mcp::artifacts::range(
        headers.get("range").and_then(|v| v.to_str().ok()),
        bytes,
    ) {
        Ok(r) => r,
        Err(_) => {
            return (
                StatusCode::RANGE_NOT_SATISFIABLE,
                [("content-range", format!("bytes */{bytes}"))],
            )
                .into_response()
        }
    };
    let digest = snapshot.digest;
    let mut file = tokio::fs::File::from_std(snapshot.file);
    if file.seek(std::io::SeekFrom::Start(start)).await.is_err() {
        return StatusCode::INTERNAL_SERVER_ERROR.into_response();
    }
    let length = end - start + 1;
    let stream = futures::stream::try_unfold(
        (file, length, principal, id, permit),
        |(mut file, left, p, id, permit)| async move {
            if left == 0 {
                return Ok::<_, std::io::Error>(None);
            }
            let cp = p.clone();
            let cid = id.clone();
            let permitted =
                tokio::task::spawn_blocking(move || crate::mcp::artifacts::authorized(&cp, &cid))
                    .await;
            if !matches!(permitted, Ok(Ok(()))) {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::PermissionDenied,
                    "ARTIFACT_ACCESS_REVOKED",
                ));
            }
            let mut buf = vec![0u8; left.min(65536) as usize];
            let n = file.read(&mut buf).await?;
            if n == 0 {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::UnexpectedEof,
                    "ARTIFACT_INCOMPLETE",
                ));
            }
            buf.truncate(n);
            Ok(Some((buf, (file, left - n as u64, p, id, permit))))
        },
    );
    let partial = headers.contains_key("range");
    let mut response = Response::builder()
        .status(if partial {
            StatusCode::PARTIAL_CONTENT
        } else {
            StatusCode::OK
        })
        .header("content-type", "application/octet-stream")
        .header("content-length", length)
        .header("etag", format!("\"{digest}\""))
        .header("accept-ranges", "bytes")
        .header("cache-control", "private, no-store")
        .header("x-content-type-options", "nosniff")
        .header("content-disposition", "attachment");
    if partial {
        response = response.header("content-range", format!("bytes {start}-{end}/{bytes}"));
    }
    response
        .body(axum::body::Body::from_stream(stream))
        .unwrap_or_else(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response())
}

/// The projection's answer to one POST: 401 without a valid session token,
/// 202 for a notification, 200 with the JSON-RPC reply otherwise.
pub async fn assist_mcp_response(
    db: &omniget_core::core::assist::db::AssistDb,
    headers: &HeaderMap,
    body: &[u8],
) -> (StatusCode, Option<serde_json::Value>) {
    let msg: serde_json::Value = match serde_json::from_slice(body) {
        Ok(v) => v,
        Err(e) => {
            // Parse errors still need a valid token: say nothing otherwise.
            if bearer_of(headers)
                .and_then(|t| omniget_core::core::assist::projection::validate(db, &t, now_ms()))
                .is_none()
            {
                return (StatusCode::UNAUTHORIZED, None);
            }
            return (
                StatusCode::BAD_REQUEST,
                Some(
                    serde_json::json!({ "jsonrpc": "2.0", "id": null, "error": { "code": -32700, "message": format!("parse error: {e}") } }),
                ),
            );
        }
    };
    match omniget_core::core::assist::projection::handle(db, bearer_of(headers).as_deref(), &msg)
        .await
    {
        Err(_) => (StatusCode::UNAUTHORIZED, None),
        Ok(Some(reply)) => (StatusCode::OK, Some(reply)),
        Ok(None) => (StatusCode::ACCEPTED, None),
    }
}

async fn assist_mcp_post(headers: HeaderMap, body: axum::body::Bytes) -> Response {
    let db = match omniget_core::core::assist::db::global() {
        Ok(db) => db,
        Err(_) => return StatusCode::SERVICE_UNAVAILABLE.into_response(),
    };
    match assist_mcp_response(&db, &headers, &body).await {
        (status, Some(v)) => (status, Json(v)).into_response(),
        (StatusCode::UNAUTHORIZED, None) => unauthorized(),
        (status, None) => status.into_response(),
    }
}

/// Sem canal SSE: quem pedir GET recebe 405 e continua só com POST.
async fn mcp_get() -> Response {
    StatusCode::METHOD_NOT_ALLOWED.into_response()
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::http::HeaderValue;

    #[test]
    fn queue_route_payload_has_no_url_secrets() {
        const S: &str = "SYNTHETIC_SECRET_b1r";
        let raw =
            format!("https://s3.test/o.mp4?X-Amz-Signature={S}&token={S}&sig={S}&igsh={S}#frag{S}");
        let mut q = crate::core::queue::DownloadQueue::new(3);
        q.enqueue(
            1,
            raw.clone(),
            "generic".into(),
            "t".into(),
            "/tmp".into(),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            std::sync::Arc::new(crate::platforms::noop::NoopDownloader),
            None,
            false,
            None,
            None,
            None,
            None,
            None,
        );
        let items = crate::core::queue::redacted_for_display(q.get_state());
        let json = serde_json::to_string(&items).unwrap();
        assert!(!json.contains(S), "{json}");
        assert!(json.contains("https://s3.test/o.mp4?"), "{json}");
        // The download itself still has the executable URL in memory.
        assert!(q.has_url(&raw));
    }

    fn header_with_auth(value: &str) -> HeaderMap {
        let mut headers = HeaderMap::new();
        headers.insert(
            "authorization",
            HeaderValue::from_str(value).expect("valid header"),
        );
        headers
    }

    #[test]
    fn token_is_url_safe_base64_with_no_padding() {
        let t = generate_token();
        assert!(t.len() >= 40);
        assert!(!t.contains('+'));
        assert!(!t.contains('/'));
        assert!(!t.contains('='));
    }

    #[test]
    fn check_bearer_accepts_valid_token() {
        let headers = header_with_auth("Bearer abc.def-ghi");
        assert!(check_bearer(&headers, "abc.def-ghi"));
    }

    #[test]
    fn check_bearer_is_case_insensitive_on_scheme() {
        let headers = header_with_auth("bearer abc");
        assert!(check_bearer(&headers, "abc"));
    }

    #[test]
    fn check_bearer_rejects_missing_header() {
        let headers = HeaderMap::new();
        assert!(!check_bearer(&headers, "abc"));
    }

    #[test]
    fn check_bearer_rejects_wrong_token() {
        let headers = header_with_auth("Bearer different");
        assert!(!check_bearer(&headers, "abc"));
    }

    #[test]
    fn check_bearer_rejects_missing_scheme_prefix() {
        let headers = header_with_auth("abc");
        assert!(!check_bearer(&headers, "abc"));
    }

    #[tokio::test]
    async fn the_assist_projection_route_wants_its_own_session_token() {
        use omniget_core::core::assist::{db::AssistDb, projection};
        let db = AssistDb::open_in_memory().unwrap();
        let list = br#"{"jsonrpc":"2.0","id":1,"method":"tools/list"}"#;
        let (status, body) = assist_mcp_response(&db, &HeaderMap::new(), list).await;
        assert_eq!(status, StatusCode::UNAUTHORIZED);
        assert!(body.is_none());
        let (status, _) = assist_mcp_response(&db, &header_with_auth("Bearer wrong"), list).await;
        assert_eq!(status, StatusCode::UNAUTHORIZED);
        let issued = projection::issue(&db, "bot", "conv", None, &[], false, 60_000).unwrap();
        let auth = header_with_auth(&format!("Bearer {}", issued.token));
        let (status, body) = assist_mcp_response(&db, &auth, list).await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(body.unwrap()["result"]["tools"], serde_json::json!([]));
        let note = br#"{"jsonrpc":"2.0","method":"notifications/initialized"}"#;
        assert_eq!(
            assist_mcp_response(&db, &auth, note).await.0,
            StatusCode::ACCEPTED
        );
        projection::revoke(&db, &issued.id);
        assert_eq!(
            assist_mcp_response(&db, &auth, list).await.0,
            StatusCode::UNAUTHORIZED
        );
    }

    #[test]
    fn build_pairing_url_uses_loopback_address() {
        assert_eq!(build_pairing_url(47720), "http://127.0.0.1:47720");
    }
}
